# Generated by Django 6.0.5 on 2026-05-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerproduct',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
