# Generated by Django 6.0.5 on 2026-05-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_offerproduct_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerproduct',
            old_name='decs',
            new_name='desc',
        ),
    ]
