# Generated by Django 6.0.5 on 2026-05-20 17:47

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_category_alter_offerproduct_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerproduct',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
